name: chat_bot
description: "NLU based ChatBot plugin for flutter apps that can be used to do various actions based on user speech input"
version: 0.1.0
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.typ.chat_bot
        pluginClass: ChatBotPlugin
